apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx
spec:
  destination:
    name: 'nginx'
    namespace: nginx
    server: https://kubernetes.default.svc
  source:
    path: .
    repoURL: https://https://github.com/unklo1200/soldesk901.git
    targetRevision: HEAD
  sources: []
  project: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: false
      selfHeal: false

#test