apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-deploy
  namespace: web
  labels:
    app: web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      imagePullSecrets:
        - name: ghcr-cred
      containers:
        - name: web
          image: ghcr.io/unklo1200/web-php-nginx:lastest
          ports:
            - containerPort: 80
