apiVersion: v1
kind: Namespace
metadata:
  name: web
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: web-sa
  namespace: web
imagePullSecrets:
  - name: ghcr-pull-secret
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-deploy
  namespace: web
  labels: { app: web }
spec:
  replicas: 1
  selector:
    matchLabels: { app: web }
  template:
    metadata:
      labels: { app: web }
    spec:
      serviceAccountName: web-sa
      nodeSelector:
        eks.amazonaws.com/nodegroup: ng-web
      imagePullSecrets:
        - name: ghcr-pull-secret
      containers:
        - name: web
          image: ghcr.io/unklo1200/web-php
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          env:
            - name: WAS_BASE_URL
              value: "http://was-svc.was.svc.cluster.local:8000"
          startupProbe:
            httpGet:
              path: /healthz.txt
              port: 80
            periodSeconds: 2
            failureThreshold: 90
            timeoutSeconds: 2
          readinessProbe:
            httpGet:
              path: /healthz.txt
              port: 80
            periodSeconds: 5
            timeoutSeconds: 2
            failureThreshold: 6
          livenessProbe:
            httpGet:
              path: /healthz.txt
              port: 80
            initialDelaySeconds: 60
            periodSeconds: 10
            timeoutSeconds: 2
            failureThreshold: 3
          resources:
            requests: { cpu: "100m", memory: "128Mi" }
            limits:   { cpu: "500m", memory: "512Mi" }
          volumeMounts:
            - name: healthz
              mountPath: /var/www/html/healthz.txt
              subPath: healthz.txt
              readOnly: true
      volumes:
        - name: healthz
          configMap:
            name: web-healthz
            items:
              - key: healthz.txt
                path: healthz.txt
---
apiVersion: v1
kind: Service
metadata:
  name: web-svc
  namespace: web
  labels: { app: web }
spec:
  type: LoadBalancer
  selector:
    app: web
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP
