apiVersion: v1
kind: Namespace
metadata:
  name: web
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: web-sa
  namespace: web
imagePullSecrets:
  - name: ghcr-pull-secret
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-deploy
  namespace: web
  labels:
    app: web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      serviceAccountName: web-sa
      nodeSelector:
        eks.amazonaws.com/nodegroup: ng-web
      imagePullSecrets:
        - name: ghcr-pull-secret
      containers:
        - name: web
          image: ghcr.io/unklo1200/web-php-nginx:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          env:
            - name: WAS_BASE_URL
              value: "http://was-svc.was.svc.cluster.local:8000"
          # More forgiving probes that only check the port is open
          startupProbe:
            tcpSocket:
              port: 80
            periodSeconds: 2
            failureThreshold: 90   # ~180s grace
            timeoutSeconds: 1
          readinessProbe:
            tcpSocket:
              port: 80
            periodSeconds: 5
            timeoutSeconds: 2
            failureThreshold: 6
          # Liveness after the container had time to warm up
          livenessProbe:
            tcpSocket:
              port: 80
            initialDelaySeconds: 60
            periodSeconds: 10
            timeoutSeconds: 2
            failureThreshold: 3
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: web-svc
  namespace: web
  labels:
    app: web
spec:
  type: ClusterIP
  selector:
    app: web
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP
