apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-deploy
  namespace: web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: web
        image: ghcr.io/unklo1200/web-php-nginx:latest
        ports:
        - containerPort: 80
      imagePullSecrets:
      - name: ghcr-pull-secret
---
apiVersion: v1
kind: Service
metadata:
  name: web-svc
  namespace: web
spec:
  type: NodePort
  selector:
    app: web
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30080
