apiVersion: apps/v1
kind: Deployment
metadata:
  name: was-deploy
  labels:
    app: was
spec:
  replicas: 2
  selector:
    matchLabels:
      app: was
  template:
    metadata:
      labels:
        app: was
    spec:
      containers:
        - name: was
          image: ghcr.io/your-id/was:latest
          ports:
            - containerPort: 8080
