apiVersion: v1
kind: Service
metadata:
  name: web-svc
  labels:
    app: web
spec:
  type: LoadBalancer   # 외부 접속 가능 (EKS면 ELB 생성)
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: web
