{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: web-alb
  namespace: web
  annotations:
    {{- range $k, $v := .Values.ingress.annotations }}
    {{ $k }}: {{ $v | quote }}
    {{- end }}
spec:
  ingressClassName: {{ .Values.ingress.className | quote }}
  rules:
    - host: {{ (index .Values.ingress.hosts 0).host | quote }}   # 또는 range .Values.ingress.hosts
      http:
        paths:
          - path: {{ (index .Values.ingress.hosts 0).paths 0).path | default "/" }}
            pathType: {{ (index .Values.ingress.hosts 0).paths 0).pathType | default "Prefix" }}
            backend:
              service:
                name: web-frontend
                port:
                  number: 80
{{- end }}

