apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: web-ing
  namespace: web
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing   # 내부면 internal
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP":80}]'
spec:
  rules:
  - host: web.projecteks.local   # 내부 도메인이면 여기에 맞게
    http:
      paths:
      - path: /api/*
        pathType: Prefix
        backend:
          service:
            name: was-svc
            port:
              number: 8000
      - path: /*
        pathType: Prefix
        backend:
          service:
            name: web-svc
            port:
              number: 80
