{{- if and .Values.redis.enabled .Values.redis.password }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.redis.secretName | default "redis-auth" }}
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  {{ .Values.redis.secretKey | default "REDIS_PASSWORD" }}: {{ .Values.redis.password | quote }}
{{- end }}
