apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: web-frontend-reader-binding
  namespace: web
subjects:
  - kind: ServiceAccount
    name: web-frontend
    namespace: appnet
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: web-frontend-reader
