apiVersion: v1
kind: Service
metadata:
  name: web-svc
  namespace: {{ .Release.Namespace }}
  labels:
    app: web
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: web
    app.kubernetes.io/instance: {{ .Release.Name }}
    app: web
  ports:
    - name: http
      port: 80
      targetPort: http
