apiVersion: v1
kind: Service
metadata:
  name: web-frontend
  namespace: web
spec:
  selector:
    app: web-frontend
  type: NodePort
  ports:
    - name: http
      port: 80
      targetPort: 8080
      nodePort: 30080
