apiVersion: v1
kind: Service
metadata:
  name: web-svc
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: web
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    app.kubernetes.io/component: frontend
    app.kubernetes.io/part-of: projecteks
    app: web
spec:
  type: {{ .Values.service.type }}
  selector: { app: web }
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: 80