apiVersion: v1
kind: Service
metadata:
  name: web-svc
  labels:
    app: web
spec:
  type: {{ .Values.service.type }}
  selector:
    app: web
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: 80
