apiVersion: v1
kind: Service
metadata:
  name: web-frontend
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: web
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: 80
