replicaCount: 2
image:
  repository: ghcr.io/unklo1200/web-updated
  tag: latest
  pullPolicy: IfNotPresent
imagePullSecrets:
- name: ghcr-pull-secret
containerPort: 8080
backend:
  protocol: http
  host: was.projecteks.local
  port: 8000
nodeSelector:
  workload: web
tolerations:
- key: dedicated
  operator: Equal
  value: web
  effect: NoSchedule
probes:
  path: /
  portName: http
resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 256Mi
ingress:

  className: alb
  annotations: {}
  hosts:
  - host: soldesk901-1.cloud
    paths:
    - path: /
      pathType: Prefix
  tls: []
mode: direct
nlbWatcher:
  enabled: true
  image: bitnami/kubectl:latest
  pollInterval: 20
  targetServiceNamespace: was
  targetServiceName: was-api-nlb
  targetPort: 80
  outFile: /opt/web-shared/api_base
redis:
  enabled: true
  host: redis.redis.svc.cluster.local
  port: 6379
  secretName: redis-auth
  secretKey: redis-password
