replicaCount: 2
image:
  repository: ghcr.io/unklo1200/web-updated
  tag: v16
  pullPolicy: IfNotPresent
imagePullSecrets:
  - name: ghcr-pull-secret
containerPort: 8080
backend:
  protocol: http
  host: was.projecteks.local
  port: 8000
nodeSelector:
  workload: web
tolerations:
  - key: dedicated
    operator: Equal
    value: web
    effect: NoSchedule
probes:
  path: /
  portName: http
resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 256Mi
ingress:
  className: alb
  annotations:
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/healthcheck-path: /
    # 필요 시 퍼블릭 서브넷 명시 (자동발견 이슈 있을 때)
    # alb.ingress.kubernetes.io/subnets: subnet-aaaa,subnet-bbbb
    external-dns.alpha.kubernetes.io/hostname: soldesk901-1.cloud
  hosts:
    - host: soldesk901-1.cloud
      paths:
        - path: /
          pathType: Prefix
  tls: []
  enabled: true
mode: direct
nlbWatcher:
  enabled: true
  image: bitnami/kubectl:latest
  pollInterval: 20
  targetServiceNamespace: was
  targetServiceName: was-api-nlb
  targetPort: 80
  outFile: /opt/web-shared/api_base
redis:
  enabled: true
  host: redis.redis.svc.cluster.local
  port: 6379
  secretName: redis-auth
  secretKey: REDIS_PASSWORD