# --- web/values.yaml (clean) ---
image:
  repository: ghcr.io/unklo1200/web-updated
  tag: "v16"
  pullPolicy: IfNotPresent

imagePullSecrets:
  - name: ghcr-pull-secret   # 네임스페이스(web)에 존재해야 함

service:
  type: ClusterIP
  port: 80

nodeSelector:
  workload: "web"

tolerations:
  - key: "dedicated"
    operator: "Equal"
    value: "web"
    effect: "NoSchedule"

affinity: {}
resources: {}

backend:
  mode: externalName
  host: "was.projecteks.local"  # external-dns(private)로 관리되는 내부 FQDN 가정

ingress:
  enabled: false
  className: alb
  annotations: {}
  hosts:
    - host: web.projecteks.local
      paths:
        - path: /
          pathType: Prefix
  tls: []

