replicaCount: 2

image:
  repository: ghcr.io/unklo1200/web-updated
  tag: v16
  pullPolicy: IfNotPresent

imagePullSecrets:
  - name: ghcr-pull-secret

# 앱이 반드시 이 포트로 리슨하도록 강제 (PORT env로도 주입됨)
containerPort: 8080

# 앱 바인딩 호스트 (HOST env)
server:
  host: 0.0.0.0

nodeSelector:
  workload: web

tolerations:
  - key: dedicated
    operator: Equal
    value: web
    effect: NoSchedule

# 서비스 타입/포트
service:
  type: ClusterIP
  port: 80

# 프로브: HTTP 대신 TCP로 완화 (안정화 후 readiness만 HTTP로 되돌려도 됨)
probes:
  path: /
  readiness:
    tcp: true
    initialDelaySeconds: 60
    periodSeconds: 10
    timeoutSeconds: 10
    failureThreshold: 20
  liveness:
    tcp: true
    initialDelaySeconds: 240
    periodSeconds: 15
    timeoutSeconds: 5
    failureThreshold: 6
  startup:
    enabled: true
    tcp: true
    failureThreshold: 120
    periodSeconds: 5
    timeoutSeconds: 3

# 리소스
resources:
  requests:
    cpu: 150m
    memory: 256Mi
  limits:
    cpu: 1000m
    memory: 512Mi

ingress:
  className: alb
  annotations:
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/healthcheck-path: /
    external-dns.alpha.kubernetes.io/hostname: soldesk901-1.cloud
  hosts:
    - host: soldesk901-1.cloud
      paths:
        - path: /
          pathType: Prefix
  tls: []
  enabled: true

# direct 모드: NLB 주소를 파일로 주입
mode: direct

# NLB watcher 설정
nlbWatcher:
  enabled: true
  image: bitnami/kubectl:latest
  pollInterval: 20
  targetServiceNamespace: was
  targetServiceName: was-api-nlb
  targetPort: 80
  outFile: /opt/web-shared/api_base

# 초기값을 써두는 initContainer on/off
initApiBaseEnabled: true

redis:
  enabled: true
  host: redis.redis.svc.cluster.local
  port: 6379
  secretName: redis-auth
  secretKey: REDIS_PASSWORD
  password: super-strong-password  # ← 웹 NS에 secret 자동 생성할 수 있도록 명시

# 추가 환경변수 필요시
extraEnv: []
