replicaCount: 2

image:
  repository: ghcr.io/unklo1200/web-updated
  tag: v16
  pullPolicy: IfNotPresent

imagePullSecrets:
  - name: ghcr-pull-secret

containerPort: 8080

nodeSelector:
  workload: web

tolerations:
  - key: dedicated
    operator: Equal
    value: web
    effect: NoSchedule

# 서비스 타입/포트 명시 (ALB는 Ingress → Service(ClusterIP)로 라우팅)
service:
  type: ClusterIP
  port: 80

# 프로브: 초기 부하/콜드스타트까지 넉넉히
probes:
  path: /
  readiness:
    initialDelaySeconds: 45
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 10
  liveness:
    tcp: true               # 템플릿에서 tcpSocket으로 분기
    initialDelaySeconds: 180
    periodSeconds: 15
    timeoutSeconds: 5
    failureThreshold: 6
  startup:
    enabled: true
    failureThreshold: 120
    periodSeconds: 5
    timeoutSeconds: 3

# 리소스 여유
resources:
  requests:
    cpu: 150m
    memory: 256Mi
  limits:
    cpu: 1000m
    memory: 512Mi

ingress:
  className: alb
  annotations:
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/healthcheck-path: /
    external-dns.alpha.kubernetes.io/hostname: soldesk901-1.cloud
  hosts:
    - host: soldesk901-1.cloud
      paths:
        - path: /
          pathType: Prefix
  tls: []
  enabled: true

mode: direct

nlbWatcher:
  enabled: true
  image: bitnami/kubectl:latest
  pollInterval: 20
  targetServiceNamespace: was
  targetServiceName: was-api-nlb
  targetPort: 80
  outFile: /opt/web-shared/api_base

redis:
  enabled: true
  host: redis.redis.svc.cluster.local
  port: 6379
  secretName: redis-auth
  secretKey: REDIS_PASSWORD
