image:
  repository: ghcr.io/unklo1200/web_http
  tag: latest
  pullSecrets:
    - ghcr-pull-secret

privateDomain: "projecteks.local"

backend:
  mode: externalName               # externalName | clusterDNS
  host: was.projecteks.local       # ← 여기만 바꾸면 경로 전환 가능

service:
  port: 80

ingress:
  enabled: true
  className: alb
  scheme: internet-facing
  targetType: ip
  hosts:
    - host: ""
      paths:
        - path: /
          pathType: Prefix
