image:
  repository: ghcr.io/unklo1200/web-updated
  tag: "latest"
  pullPolicy: IfNotPresent

replicaCount: 2

podAnnotations: {}
deploymentAnnotations: {}

resources:
  requests:
    cpu: "100m"
    memory: "128Mi"
  limits:
    cpu: "500m"
    memory: "512Mi"

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  className: alb
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP":80}]'
    alb.ingress.kubernetes.io/load-balancer-attributes: deletion_protection.enabled=true
  hosts:
    - paths:
        - path: /
          pathType: Prefix
  tls: []

# Terraform에서 주입하는 사설 도메인 (ExternalDNS private HZ)
privateDomain: "projecteks.local"

# web → was 호출 연결 방식
backend:
  mode: externalName
  host: "was.projecteks.local"

hpa:
  enabled: true
  minReplicas: 2
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 60
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 70

nodeSelector:
  role: web

tolerations:
  - key: "role"
    operator: "Equal"
    value: "web"
    effect: "NoSchedule"

affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
        - matchExpressions:
            - key: role
              operator: In
              values: ["web"]
