apiVersion: v1
kind: Namespace
metadata:
  name: was
---
apiVersion: v1
kind: Secret
metadata:
  name: was-db-secret
  namespace: was
type: Opaque
stringData:
  # Credentials (as requested)
  DB_USERNAME: "admin"
  DB_PASSWORD: "adminadmin"
  # Common aliases some apps expect
  MYSQL_USER: "admin"
  MYSQL_PASSWORD: "adminadmin"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: was-db-config
  namespace: was
data:
  # RDS endpoint & database name
  DB_HOST: "test.cl6k4y6qsqhk.ap-northeast-2.rds.amazonaws.com"
  DB_NAME: "test"
  # Common aliases some apps expect
  MYSQL_HOST: "test.cl6k4y6qsqhk.ap-northeast-2.rds.amazonaws.com"
  MYSQL_DATABASE: "test"
  # If your app uses a single URL, consider setting DATABASE_URL directly in the Deployment env (commented example below).
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: was-deploy
  namespace: was
  labels:
    app: was
spec:
  replicas: 1
  selector:
    matchLabels:
      app: was
  template:
    metadata:
      labels:
        app: was
    spec:
      containers:
        - name: was
          # TODO: replace with your actual WAS image if different
          image: ghcr.io/unklo1200/was:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
          envFrom:
            - secretRef:
                name: was-db-secret
            - configMapRef:
                name: was-db-config
          # If your app expects a single DATABASE_URL, uncomment and adjust the driver:
          # env:
          #   - name: DATABASE_URL
          #     value: "mysql+pymysql://admin:your passwd@test.cl6k4y6qsqhk.ap-northeast-2.rds.amazonaws.com/test"
          readinessProbe:
            httpGet:
              path: /api/health
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /api/health
              port: 8000
            initialDelaySeconds: 30
            periodSeconds: 20
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
      # If pulling from a private GHCR, add imagePullSecrets here
      # imagePullSecrets:
      #   - name: ghcr-creds
---
apiVersion: v1
kind: Service
metadata:
  name: was-svc
  namespace: was
  labels:
    app: was
spec:
  type: ClusterIP
  selector:
    app: was
  ports:
    - name: http
      port: 8000
      targetPort: 8000
      protocol: TCP
---
# (Optional) Allow only the 'web' namespace to reach WAS over port 8000
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: was-allow-web-only
  namespace: was
spec:
  podSelector:
    matchLabels:
      app: was
  policyTypes:
    - Ingress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: web
      ports:
        - protocol: TCP
          port: 8000
