apiVersion: apps/v1
kind: Deployment
metadata:
  name: was
  namespace: was
  labels:
    app: was
spec:
  replicas: 2
  selector:
    matchLabels:
      app: was
  template:
    metadata:
      labels:
        app: was
    spec:
      # GHCR pull secret
      imagePullSecrets:
        - name: ghcr-cred

      # was 전용 노드에만 스케줄
      nodeSelector:
        role: "was"
      tolerations:
        - key: "role"
          operator: "Equal"
          value: "was"
          effect: "NoSchedule"

      containers:
        - name: was
          image: ghcr.io/unklo1200/was-updated:v10
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8000
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          # DB 연결 등 환경이 있으면 여기서 주입
          # envFrom:
          #   - secretRef:
          #       name: was-db-secret

---
apiVersion: v1
kind: Service
metadata:
  name: was
  namespace: was
  labels:
    app: was
spec:
  type: ClusterIP
  selector:
    app: was
  ports:
    - name: http
      port: 8000
      targetPort: http
