apiVersion: v1
kind: Namespace
metadata:
  name: was
---
apiVersion: v1
kind: Secret
metadata:
  name: was-db-secret
  namespace: was
type: Opaque
stringData:
  username: "admin"
  password: "adminadmin"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: was-deploy
  namespace: was
  labels:
    app: was
spec:
  replicas: 1
  selector:
    matchLabels:
      app: was
  template:
    metadata:
      labels:
        app: was
    spec:
        imagePullSecrets:
        - name: ghcr-secret
      containers:
        - name: was
          image: ghcr.io/unklo1200/was-v1:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
          env:
            - name: DB_HOST
              value: "test.cl6k4y6qsqhk.ap-northeast-2.rds.amazonaws.com"   # ← 예: mydb.abc123.ap-northeast-2.rds.amazonaws.com
            - name: DB_PORT
              value: "3306"
            - name: DB_NAME
              value: "test"
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: was-db-secret
                  key: username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: was-db-secret
                  key: password
          readinessProbe:
            httpGet:
              path: /api/health
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /api/health
              port: 8000
            initialDelaySeconds: 15
            periodSeconds: 20
          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: was-svc
  namespace: was
  labels:
    app: was
spec:
  type: NodePort
  selector:
    app: was
  ports:
    - name: http
      port: 8000
      targetPort: 8000
      nodePort: 30081
