apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: web-frontend-reader
  namespace: {{ .Release.Namespace }}
rules:
  - apiGroups: [""]
    resources: ["services"]
    verbs: ["get","list","watch"]
